#!/usr/bin/env python3
"""
gen_module_docs.py - generate a symbol PNG + README for EVERY module in the tree.

WHY THIS EXISTS
    module_doc.py documents one module. Pointing it at two modules by hand
    proves the tool works; it does not document the design. This walks the
    whole tree so the documentation cannot quietly cover 2 modules out of 432
    while looking finished.

WHAT IT PRODUCES
    For <component>/circuit/FOO.v:
        <component>/circuit/doc/FOO.png
        <component>/circuit/doc/FOO.md

WHAT IT SKIPS, AND SAYS SO
    - anything under a sim/ directory and any *_tb.v  (testbenches are not
      modules of the design)
    - VENDOR-GENERATED IP: Xilinx MIG (ip/ trees, mig_7series_*), Gowin PLLs,
      and Vivado's .Xil scratch. Those are not our design, they are hundreds of
      files, and documenting them buries the 300-odd modules that ARE ours.
    - git SUBMODULES (any folder below the top with its own .git entry, e.g.
      fpga/mega65/m2m). They are other people's repos: writing doc/ folders
      into them would leave their working trees dirty, and the code is not
      ours to document.
    - the MiSTer FRAMEWORK in fpga/mister/sys/. It is copied as-is from
      Template_MiSTer (GPL-2.0, see fpga/mister/README.md); every MiSTer core
      must ship it untouched, so it is not ours to document.
    - Quartus IP wizard output: any .v with a same-named .qip beside it
      (fpga/mister/rtl/pll.v, rtl/pll/pll_0002.v). The wizard wrote them;
      a regenerate would overwrite them.
    - the Template_MiSTer demo core left in fpga/mister/rtl (mycore.v,
      lfsr.v, cos.sv). Byte-identical to upstream (checked 30-SEP-2026),
      and not in files.qip, so not even part of our build.
    - build/ and lint/ folders: build output (the per-build banner ROM copy
      in build/) and lint scratch. Git ignores them; the real source sits
      elsewhere and gets its own doc.
    - lint-only stand-ins for vendor primitives (*_stub.v, *_stubs.v, e.g.
      qmtech-a35t/rtl/lint_stubs.v with BUFG and MMCME2_BASE). They are
      hollow models that exist only so Verilator can lint; a doc under the
      vendor's part name would describe a part that is not really there.
    - files with no module declaration
    Every skip and every failure is listed at the end. A sweep that silently
    drops files is worse than no sweep, because the count looks complete.

THE INDEX
    After a whole-tree sweep it also writes Verilog/MODULES.md: every
    generated module doc, grouped by area, with its one-line description and
    a link. Without it the docs are published on the website but nothing
    links to them, so nobody finds them. The index is built from the docs
    themselves (a doc counts if it carries module_doc.py's "Generated by"
    line), so it cannot list a module that has no doc or miss one that has.
    --index-only rebuilds just the index.

THE HIERARCHY
    After the index, a whole-tree sweep runs tests/gen_hierarchy.py: yosys
    elaborates every build top (simulation and each FPGA board) with that
    top's own file list and defines, and from that it writes
    Verilog/HIERARCHY.md (one tree per top) and a navigation block on every
    module doc (where the module sits, what uses it, what it contains).
    module_doc.py writes a doc WITHOUT that block, so this sweep is also what
    puts the block back after a doc was regenerated on its own.
    Needs yosys (~/oss-cad-suite) and tclsh, so run it in WSL.

THE ONE COMMAND (docs, MODULES.md, HIERARCHY.md and the navigation blocks)
    cd Verilog
    python3 tests/gen_module_docs.py

USAGE
    cd Verilog
    python3 tests/gen_module_docs.py                 # whole tree + index + hierarchy
    python3 tests/gen_module_docs.py --root DELILAH-CPU
    python3 tests/gen_module_docs.py --dry-run
    python3 tests/gen_module_docs.py --jobs 8
    python3 tests/gen_module_docs.py --index-only    # just Verilog/MODULES.md
    python3 tests/gen_module_docs.py --hierarchy-only  # HIERARCHY.md + nav blocks
    python3 tests/gen_module_docs.py --no-hierarchy  # skip the yosys step
"""

import argparse
import concurrent.futures as cf
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VROOT = os.path.dirname(HERE)                     # Verilog/
MODULE_DOC = os.path.join(HERE, "module_doc.py")

MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)", re.M)

# Folders that only ever hold build output or lint scratch - see WHAT IT SKIPS.
SKIP_DIR_NAMES = ("build", "lint")

# Third-party trees, as paths relative to Verilog/. The MiSTer framework must
# ship untouched, so it gets no doc/ folders - see WHAT IT SKIPS.
SKIP_TREES = ("fpga/mister/sys",)

# The Template_MiSTer demo core, still in the tree but not built and not ours
# (byte-identical to upstream) - see WHAT IT SKIPS.
SKIP_FILES = ("fpga/mister/rtl/mycore.v",
              "fpga/mister/rtl/lfsr.v",
              "fpga/mister/rtl/cos.sv")


def find_sources(root):
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        # a submodule has its own .git entry - skip it and everything under
        # it (see WHAT IT SKIPS above). The repo top itself is above VROOT,
        # so it is never seen here.
        if os.path.exists(os.path.join(dirpath, ".git")):
            dirnames[:] = []
            continue
        parts = set(dirpath.replace("\\", "/").split("/"))
        if "sim" in parts or "obj_dir" in parts or ".git" in parts:
            continue
        if "ip" in parts or ".Xil" in parts or "user_design" in parts:
            continue   # vendor-generated IP - see WHAT IT SKIPS above
        # third-party trees (the MiSTer framework): drop the whole subtree
        rel_dir = os.path.relpath(dirpath, VROOT).replace("\\", "/")
        if any(rel_dir == t or rel_dir.startswith(t + "/") for t in SKIP_TREES):
            dirnames[:] = []
            continue
        # build/ and lint/ hold build output and lint scratch, never source
        dirnames[:] = [d for d in dirnames
                       if d not in ("sim", ".git", "doc") + SKIP_DIR_NAMES
                       and not d.startswith("obj_dir")]
        for fn in filenames:
            # .sv too: the MiSTer core top (fpga/mister/nd120.sv, module emu)
            # is the one SystemVerilog file of ours, and the hierarchy page
            # starts that board's tree at it
            if not fn.endswith((".v", ".sv")):
                continue
            if fn.endswith("_tb.v"):
                continue
            if fn.startswith("mig_7series_") or fn.startswith("gowin_"):
                continue   # vendor IP that lives outside an ip/ directory
            # Quartus IP wizard output: the wizard writes a .qip next to it
            if os.path.exists(os.path.join(dirpath, os.path.splitext(fn)[0] + ".qip")):
                continue
            # lint-only stand-ins for vendor primitives (BUFG, MMCME2_BASE, rPLL)
            if fn.endswith("_stub.v") or fn.endswith("_stubs.v"):
                continue
            # the unused Template_MiSTer demo core
            if (rel_dir + "/" + fn) in SKIP_FILES:
                continue
            out.append(os.path.join(dirpath, fn))
    return sorted(out)


def modules_in(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return MODULE_RE.findall(fh.read())
    except OSError:
        return []


def one(path, dry):
    mods = modules_in(path)
    if not mods:
        return ("skip", path, "no module declaration")
    outdir = os.path.join(os.path.dirname(path), "doc")
    if dry:
        return ("ok", path, "would write %d module(s) to %s" % (len(mods), outdir))
    os.makedirs(outdir, exist_ok=True)
    made = []
    for m in mods:
        # path is absolute here. That is fine: module_doc.py turns it into a
        # repo-relative path before it writes the doc, so no machine path
        # (/mnt/<drive>/..., <drive>:\...) ends up in a committed file.
        cmd = [sys.executable, MODULE_DOC, path, "-o", outdir, "--module", m]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        if r.returncode != 0:
            err = (r.stderr or r.stdout).strip().splitlines()
            return ("fail", path, "%s: %s" % (m, err[-1] if err else "exit %d" % r.returncode))
        made.append(m)
    return ("ok", path, ", ".join(made))


INDEX_PATH = os.path.join(VROOT, "MODULES.md")

# The line module_doc.py puts in every doc it writes. Only files that carry it
# are listed, so hand-written notes that happen to sit in a doc/ folder are
# left out.
GENERATED_MARK = "Generated by `Verilog/tests/module_doc.py`"

# Area titles for the index, keyed by the first folder under Verilog/.
# fpga/<board> is handled in area_of(). Anything not listed uses its folder
# name, so a new top folder still shows up.
AREA_TITLES = {
    "doc": "Top level (the whole machine)",
    "DELILAH-CPU": "DELILAH CPU gate array (CGA)",
    "DECODE-GateArray": "Decoder gate array (DGA)",
    "CPU-BOARD-3202": "CPU board 3202D",
    "PAL": "PAL chips",
    "Shared": "Shared chips and support logic",
    "ND-BUS-DEVICES": "ND-bus devices (floppy, Winchester, tape)",
    "SD-FAT": "SD card and FAT file system",
    "Terminals": "Terminals (TDV2200 screen and keyboard)",
}
AREA_ORDER = ["doc", "DELILAH-CPU", "DECODE-GateArray", "CPU-BOARD-3202",
              "PAL", "Shared", "ND-BUS-DEVICES", "SD-FAT", "Terminals"]


def area_of(rel):
    """rel is a path relative to Verilog/, with forward slashes."""
    parts = rel.split("/")
    if parts[0] == "fpga" and len(parts) > 2:
        return "fpga/" + parts[1]
    return parts[0]


def area_title(key):
    if key.startswith("fpga/"):
        return "FPGA board: " + key.split("/", 1)[1]
    return AREA_TITLES.get(key, key)


def area_sort_key(key):
    if key in AREA_ORDER:
        return (0, AREA_ORDER.index(key), key)
    if key.startswith("fpga/"):
        return (2, 0, key)
    return (1, 0, key)


def read_doc(path):
    """Return (module, source, first description line) for a generated doc,
    or None when the file is not one module_doc.py wrote."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return None
    text = "\n".join(lines)
    if GENERATED_MARK not in text or not lines or not lines[0].startswith("# "):
        return None
    module = lines[0][2:].strip()
    source = ""
    desc_lines = []
    in_desc = False
    for ln in lines:
        if ln.startswith("Source: `") and not source:
            source = ln[len("Source: `"):].rstrip("`").strip()
        elif ln.strip() == "## Description":
            in_desc = True
        elif in_desc:
            if ln.startswith("## "):
                break
            if ln.strip():
                desc_lines.append(ln.strip())
    return module, source, pick_description(desc_lines)


def pick_description(desc_lines):
    """One line that says what the module is.
    Modules drawn from the schematics share a header: the project name
    ("ND120 CPU, MM&M" / "ND120 CGA (...)"), the sheet path ("BIF/BCTL"),
    then the sheet TITLE ("BUS INTERFACE"), then page and sheet numbers. The
    first line is the same for dozens of modules and says nothing, so take
    the title. Hand-written modules start with a real sentence: take that."""
    if not desc_lines:
        return ""
    line = desc_lines[0]
    if line.startswith("ND120"):
        # skip the sheet path and the page/sheet/review/author lines; some
        # sheets have no title, and then the sheet path is the best name left
        path = ""
        title = ""
        for ln in desc_lines[1:]:
            low = ln.lower()
            # the review/author lines end the header; what follows is the
            # body text, never the title
            if low.startswith(("last reviewed", "ronny hansen")):
                break
            if low.startswith(("page ", "sheet ")):
                continue
            if "/" in ln and " " not in ln:
                path = path or ln.lstrip("/")
                continue
            title = ln
            break
        line = title or path or line
    return line if len(line) <= 110 else line[:107].rstrip() + "..."


def cell(s):
    # keep a table cell on one line and stop a "|" from splitting it
    return s.replace("|", "\\|").strip()


def write_index():
    """Write Verilog/MODULES.md from every generated doc under Verilog/.
    Returns the number of modules listed."""
    rows = {}
    for dirpath, dirnames, filenames in os.walk(VROOT):
        # the same submodule rule as find_sources(): not ours, not listed
        if dirpath != VROOT and os.path.exists(os.path.join(dirpath, ".git")):
            dirnames[:] = []
            continue
        # the same skips as find_sources(), so a leftover doc in a skipped
        # place (an old lint/doc/, vendor ip/) is never listed
        rel_dir = os.path.relpath(dirpath, VROOT).replace("\\", "/")
        if any(rel_dir == t or rel_dir.startswith(t + "/") for t in SKIP_TREES):
            dirnames[:] = []
            continue
        dirnames[:] = [d for d in dirnames
                       if d not in ("sim", ".git", "ip", ".Xil", "user_design")
                       + SKIP_DIR_NAMES and not d.startswith("obj_dir")]
        if os.path.basename(dirpath) != "doc":
            continue
        for fn in filenames:
            if not fn.endswith(".md"):
                continue
            path = os.path.join(dirpath, fn)
            got = read_doc(path)
            if got is None:
                continue
            rel = os.path.relpath(path, VROOT).replace("\\", "/")
            rows.setdefault(area_of(rel), []).append((got[0], rel, got[1], got[2]))

    total = sum(len(v) for v in rows.values())
    out = []
    out.append("# Verilog modules")
    out.append("")
    out.append("> Generated by `Verilog/tests/gen_module_docs.py` from the module docs.")
    out.append("> Do not edit by hand - run `python3 tests/gen_module_docs.py --index-only`")
    out.append("> from `Verilog/` after the docs change.")
    out.append("")
    out.append("Every module of the design has its own page: what it is, a table of")
    out.append("its ports, and a picture of its symbol. Each page is made from the")
    out.append("`//!` comments in the module's source. %d modules in %d areas."
               % (total, len(rows)))
    out.append("")
    out.append("What sits inside what, for the simulation and for every FPGA board,")
    out.append("is on [HIERARCHY.md](HIERARCHY.md) (made from a yosys elaboration).")
    out.append("")
    areas = sorted(rows, key=area_sort_key)
    for key in areas:
        out.append("- [%s](#%s) (%d)" % (area_title(key), anchor(area_title(key)),
                                          len(rows[key])))
    out.append("")
    for key in areas:
        out.append("## %s" % area_title(key))
        out.append("")
        out.append("| Module | What it is | Source |")
        out.append("|---|---|---|")
        for module, rel, source, desc in sorted(rows[key], key=lambda r: r[0].lower()):
            src = source[len("Verilog/"):] if source.startswith("Verilog/") else source
            out.append("| [%s](%s) | %s | `%s` |"
                       % (cell(module), rel, cell(desc) or "-", cell(src)))
        out.append("")
    with open(INDEX_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    return total


def anchor(title):
    # GitHub/Jekyll heading anchors: lower case, spaces to "-", drop the rest
    a = title.lower().strip()
    a = re.sub(r"[^a-z0-9 _-]", "", a)
    return a.replace(" ", "-")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=VROOT,
                    help="subtree to sweep (default: the whole Verilog tree)")
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) // 2))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--index-only", action="store_true",
                    help="only rebuild Verilog/MODULES.md from the existing docs")
    ap.add_argument("--hierarchy-only", action="store_true",
                    help="only rebuild Verilog/HIERARCHY.md and the navigation "
                         "blocks on the existing docs (runs yosys)")
    ap.add_argument("--no-hierarchy", action="store_true",
                    help="skip the yosys hierarchy step of a whole-tree sweep")
    args = ap.parse_args()

    if args.index_only:
        n = write_index()
        print("wrote %s: %d modules" % (os.path.relpath(INDEX_PATH, VROOT), n))
        return 0
    if args.hierarchy_only:
        return run_hierarchy()

    root = args.root if os.path.isabs(args.root) else os.path.join(VROOT, args.root)
    srcs = find_sources(root)
    print("sweeping %d Verilog source files under %s" % (len(srcs), root))
    print("jobs: %d%s" % (args.jobs, "   (dry run)" if args.dry_run else ""))

    ok, skipped, failed = [], [], []
    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        futs = {ex.submit(one, s, args.dry_run): s for s in srcs}
        done = 0
        for fut in cf.as_completed(futs):
            done += 1
            try:
                kind, path, note = fut.result()
            except Exception as exc:                      # noqa: BLE001
                kind, path, note = "fail", futs[fut], repr(exc)
            rel = os.path.relpath(path, VROOT)
            if kind == "ok":
                ok.append((rel, note))
            elif kind == "skip":
                skipped.append((rel, note))
            else:
                failed.append((rel, note))
            if done % 25 == 0 or done == len(srcs):
                print("  %d/%d  ok=%d skip=%d fail=%d"
                      % (done, len(srcs), len(ok), len(skipped), len(failed)))

    print("\n" + "=" * 70)
    print("documented : %d files" % len(ok))
    print("skipped    : %d files" % len(skipped))
    print("FAILED     : %d files" % len(failed))
    if skipped:
        print("\nskipped (no module declaration):")
        for rel, note in sorted(skipped)[:40]:
            print("  %s" % rel)
        if len(skipped) > 40:
            print("  ... and %d more" % (len(skipped) - 40))
    if failed:
        print("\nFAILURES - these are NOT documented:")
        for rel, note in sorted(failed):
            print("  %-60s %s" % (rel, note))
    print("=" * 70)
    # the index covers the whole tree, so only a whole-tree sweep rewrites it
    if not args.dry_run and os.path.normpath(root) == os.path.normpath(VROOT):
        n = write_index()
        print("wrote %s: %d modules" % (os.path.relpath(INDEX_PATH, VROOT), n))
        # the docs were just rewritten without their navigation blocks, so
        # the hierarchy step is what puts them back (see THE HIERARCHY)
        if not args.no_hierarchy:
            if run_hierarchy() != 0:
                return 1
    return 1 if failed else 0


def run_hierarchy():
    """Run tests/gen_hierarchy.py: HIERARCHY.md + the navigation blocks."""
    sys.path.insert(0, HERE)
    import gen_hierarchy                                   # noqa: E402
    print("\nhierarchy: elaborating every build top with yosys")
    return gen_hierarchy.main([])


if __name__ == "__main__":
    sys.exit(main())
